/** @jsxImportSource theme-ui */
import { Dialog, Transition } from '@headlessui/react'
import Head from 'next/head'
import Image from 'next/image'
import React, { Fragment, useRef, useState } from 'react'
import { Button } from 'theme-ui'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const completeButtonRef = useRef();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          <Button
            onClick={() => {
              setIsOpen(true);
            }}>
            Open Me
          </Button>
        </p>

        <Transition show={isOpen} as={Fragment}>
        <Dialog
          as="div"
          initialFocus={completeButtonRef}
          static
          open={isOpen}
          onClose={() => setIsOpen(false)}
          sx={{
            position: `fixed`,
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
            zIndex: 10,
            overflowY: 'auto',
          }}>
          <div sx={{ px: 4, textAlign: "center", minHeight: "100vh"}}>
            <Transition.Child
              as={Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0"
              enterTo="opacity-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100"
              leaveTo="opacity-0">
              <Dialog.Overlay
                sx={{
                  position: 'fixed',
                  top: 0,
                  right: 0,
                  bottom: 0,
                  left: 0,
                }}
              />
            </Transition.Child>

            {/* This element is to trick the browser into centering the modal contents. */}
            <span
              sx={{
                display: 'inline-block',
              }}
              aria-hidden="true">
              &#8203;
            </span>
            <Transition.Child
              as={Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0 scale-95"
              enterTo="opacity-100 scale-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100 scale-100"
              leaveTo="opacity-0 scale-95">
              <div
                sx={{
                  p: 6,
                  my: 8,
                  verticalAlign: "middle",
                  display: "inline-block",
                  width: "half",
                  overflow: "hidden",
                  textAlign: "left",
                  backgroundColor: "white",
                  transitionProperty: "all",
                  transitionDuration: "150ms",
                  transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
                  transform: "translateX(0) translateY(0) rotate(0) skewX(0) skewY(0) scaleX(1) scaleY(1)",
                  borderRadius: "0.5rem",
                }}
                >
                <Dialog.Title as="h3">Payment successful</Dialog.Title>
                <div sx={{ mt: 2, }}>
                  <p>
                    Your payment has been successfully submitted. We’ve sent
                    your an email with all of the details of your order.
                  </p>
                </div>

                <div sx={{ mt: 4,}}>
                  <Button
                    variant="outlineSecondary"
                    type="button"
                    ref={completeButtonRef}
                    onClick={() => setIsOpen(false)}>
                    Got it, thanks!
                  </Button>
                </div>
              </div>
            </Transition.Child>
          </div>
        </Dialog>
      </Transition>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
